//
// Created by Da Li on 2020/3/9.
//

#ifndef SHARED_H__
#define SHARED_H__

// automatically generated by cmake
// by the GENERATE_EXPORT_HEADER macro
#include "shared_EXPORTS.h"
#include <cstdio>
#include <cstring>
#include <plibsys.h>
#include <psocket.h>

#define MAX_MESSAGE_LENGTH 10000
#define SERVER_PORT 4444

extern "C" char* pathRestorationMethod(char const *string);

#endif
